{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  POSTGRES_DB: {{ .Values.db.name }}
  # Construct full connection URL for easier consumption by apps
  # Format: postgres://user:password@service-name:port/dbname?sslmode=disable
  DB_URL: "postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Release.Name }}:{{ .Values.db.port }}/{{ .Values.db.name }}?sslmode=disable"
{{- end }}
